export const productImages: Record<string, any> = {
    coat1_0: require('../assets/products/clothing/coats/coat1_0.png'),
    coat2_0: require('../assets/products/clothing/coats/coat2_0.png'),
    coat3_0: require('../assets/products/clothing/coats/coat3_0.jpg'),
    coat5_0: require('../assets/products/clothing/coats/coat5_0.jpg'),
    coat6_0: require('../assets/products/clothing/coats/coat6_0.jpg'),
    coat7_0: require('../assets/products/clothing/coats/coat7_0.jpg'),
    coat8_0: require('../assets/products/clothing/coats/coat8_0.jpg'),
    coat8_1: require('../assets/products/clothing/coats/coat8_1.jpg'),
    coat8_2: require('../assets/products/clothing/coats/coat8_2.jpg'),
    coat8_3: require('../assets/products/clothing/coats/coat8_3.jpg'),
    coat9_0: require('../assets/products/clothing/coats/coat9_0.jpg'),
    coat10_0: require('../assets/products/clothing/coats/coat10_0.jpg'),
    coat11_0: require('../assets/products/clothing/coats/coat11_0.jpg'),
    coat12_0: require('../assets/products/clothing/coats/coat12_0.jpg'),
    coat13_0: require('../assets/products/clothing/coats/coat13_0.jpg'),
    coat13b_0: require('../assets/products/clothing/coats/coat13b_0.jpg'),
    coat14_0: require('../assets/products/clothing/coats/coat14_0.jpg'),

    // jeans1_0: require('../assets/products/clothing/jeans/jeans1_0.png'),
    // jeans2_0: require('../assets/products/clothing/jeans/jeans2_0.png'),
    // jeans3_0: require('../assets/products/clothing/jeans/jeans3_0.png'),
    // jeans4_0: require('../assets/products/clothing/jeans/jeans4_0.png'),
    // jeans5_0: require('../assets/products/clothing/jeans/jeans5_0.png'),
    // jeans6_0: require('../assets/products/clothing/jeans/jeans6_0.png'),
    //
    // top1_0: require('../assets/products/clothing/tops/top1_0.png'),
    // top1_1: require('../assets/products/clothing/tops/top1_1.png'),
    // top1_2: require('../assets/products/clothing/tops/top1_2.png'),
    // top1_3: require('../assets/products/clothing/tops/top1_3.png'),
    // top1_4: require('../assets/products/clothing/tops/top1_4.png'),
    // top2_0: require('../assets/products/clothing/tops/top2_0.png'),
    // top2_1: require('../assets/products/clothing/tops/top2_1.png'),
    // top2_2: require('../assets/products/clothing/tops/top2_2.png'),
    // top2_3: require('../assets/products/clothing/tops/top2_3.png'),
    // top3_0: require('../assets/products/clothing/tops/top3_0.png'),
    // top4_0: require('../assets/products/clothing/tops/top4_0.png'),
    // top5_0: require('../assets/products/clothing/tops/top5_0.png'),
    // top6_0: require('../assets/products/clothing/tops/top6_0.png'),
    // top7_0: require('../assets/products/clothing/tops/top7_0.png'),
    // top8_0: require('../assets/products/clothing/tops/top8_0.png'),
    //
    // trousers1_0: require('../assets/products/clothing/trousers/trousers1_0.png'),
    // trousers2_0: require('../assets/products/clothing/trousers/trousers2_0.png'),
    // trousers3_0: require('../assets/products/clothing/trousers/trousers3_0.png'),
    // trousers4_0: require('../assets/products/clothing/trousers/trousers4_0.png'),
    // trousers5_0: require('../assets/products/clothing/trousers/trousers5_0.png'),
    //
    // shirt1_0: require('../assets/products/clothing/tshirts/shirt1_0.png'),
    // shirt2_0: require('../assets/products/clothing/tshirts/shirt2_0.png'),
    // shirt3_0: require('../assets/products/clothing/tshirts/shirt3_0.png'),
    // shirt4_0: require('../assets/products/clothing/tshirts/shirt4_0.png'),
    // shirt5_0: require('../assets/products/clothing/tshirts/shirt5_0.png'),
    // shirt6_0: require('../assets/products/clothing/tshirts/shirt6_0.png'),
};