export const productImages: Record<string, any> = {
    coat1_0: require('../assets/products/clothing/coats/coat1_0.png'),
    coat2_0: require('../assets/products/clothing/coats/coat2_0.png'),
    coat3_0: require('../assets/products/clothing/coats/coat3_0.jpg'),
    coat5_0: require('../assets/products/clothing/coats/coat5_0.jpg'),
    coat6_0: require('../assets/products/clothing/coats/coat6_0.jpg'),
    coat7_0: require('../assets/products/clothing/coats/coat7_0.jpg'),
    coat8_0: require('../assets/products/clothing/coats/coat8_0.jpg'),
    coat8_1: require('../assets/products/clothing/coats/coat8_1.jpg'),
    coat8_2: require('../assets/products/clothing/coats/coat8_2.jpg'),
    coat8_3: require('../assets/products/clothing/coats/coat8_3.jpg'),
    coat9_0: require('../assets/products/clothing/coats/coat9_0.jpg'),
    coat10_0: require('../assets/products/clothing/coats/coat10_0.jpg'),
    coat11_0: require('../assets/products/clothing/coats/coat11_0.jpg'),
    coat12_0: require('../assets/products/clothing/coats/coat12_0.jpg'),
    coat13_0: require('../assets/products/clothing/coats/coat13_0.jpg'),
    coat13b_0: require('../assets/products/clothing/coats/coat13b_0.jpg'),
    coat14_0: require('../assets/products/clothing/coats/coat14_0.jpg'),

    jeans1_0: require('../assets/products/clothing/jeans/jeans1_0.jpg'),
    jeans2_0: require('../assets/products/clothing/jeans/jeans2_0.jpg'),
    jeans3_0: require('../assets/products/clothing/jeans/jeans3_0.jpg'),
    jeans4_0: require('../assets/products/clothing/jeans/jeans4_0.jpg'),
    jeans5_0: require('../assets/products/clothing/jeans/jeans5_0.jpg'),
    jeans6_0: require('../assets/products/clothing/jeans/jeans6_0.jpg'),

    top1_0: require('../assets/products/clothing/tops/top1_0.jpg'),
    top1_1: require('../assets/products/clothing/tops/top1_1.jpg'),
    top1_2: require('../assets/products/clothing/tops/top1_2.jpg'),
    top1_3: require('../assets/products/clothing/tops/top1_3.jpg'),
    top1_4: require('../assets/products/clothing/tops/top1_4.jpg'),
    top2_0: require('../assets/products/clothing/tops/top2_0.jpg'),
    top2_1: require('../assets/products/clothing/tops/top2_1.jpg'),
    top2_2: require('../assets/products/clothing/tops/top2_2.jpg'),
    top2_3: require('../assets/products/clothing/tops/top2_3.jpg'),
    top3_0: require('../assets/products/clothing/tops/top3_0.jpg'),
    top4_0: require('../assets/products/clothing/tops/top4_0.jpg'),
    top5_0: require('../assets/products/clothing/tops/top5_0.jpg'),
    top6_0: require('../assets/products/clothing/tops/top6_0.jpg'),
    top7_0: require('../assets/products/clothing/tops/top7_0.jpg'),
    top8_0: require('../assets/products/clothing/tops/top8_0.jpg'),

    trousers1_0: require('../assets/products/clothing/trousers/trousers1_0.jpg'),
    trousers2_0: require('../assets/products/clothing/trousers/trousers2_0.jpg'),
    trousers3_0: require('../assets/products/clothing/trousers/trousers3_0.jpg'),
    trousers4_0: require('../assets/products/clothing/trousers/trousers4_0.jpg'),
    trousers5_0: require('../assets/products/clothing/trousers/trousers5_0.jpg'),

    shirt1_0: require('../assets/products/clothing/tshirts/shirt1_0.jpg'),
    shirt2_0: require('../assets/products/clothing/tshirts/shirt2_0.jpg'),
    shirt3_0: require('../assets/products/clothing/tshirts/shirt3_0.jpg'),
    shirt4_0: require('../assets/products/clothing/tshirts/shirt4_0.jpg'),
    shirt5_0: require('../assets/products/clothing/tshirts/shirt5_0.jpg'),
    shirt6_0: require('../assets/products/clothing/tshirts/shirt6_0.jpg'),


    heels1_0: require('../assets/products/clothing/heels/heels1_0.png'),
    heels2_0: require('../assets/products/clothing/heels/heels2_0.png'),
    sneakers1_0: require('../assets/products/clothing/sneakers/sneakers1_0.png'),
    sneakers2_0: require('../assets/products/clothing/sneakers/sneakers2_0.png'),

    boots1_0: require('../assets/products/clothing/boots/boots1_0.png'),
    boots2_0: require('../assets/products/clothing/boots/boots2_0.png'),
    };